### ISSUE TITLE
Help with building/usage

### ISSUE THREAD

**Issue by NealeTools** [stefanbylund/zxnext_bmp_tools#1]
Hi Stefan, This tool looks great! I have used 320.bas written by Johnny McGibbets with some files he created. However, I would like to make some of my own 320x256 nxi files. I am running macOS.

I have followed the instructions in the readme, and appear to have built the correct files in Terminal (no error reported), but I cannot get the "nextraw" command to be recognised. Any ideas?
Thanks!

**Comment by Xalior** [comment]
Compiling a tool doesn’t automatically make it available. You need to
either move it into a directory in your path, or specifically tell your
shell the folder to execute it from - in your case that appears to be the
current one.

**Comment by NealeTools** [comment]
Thanks for the swift response. And, apologies - I am far from a Unix expert!
The compiled tool is in the directory in which I am trying to execute it from...so I assumed it should work.
Following your comments: it does now work if I add the explicit path to nextraw and to the source.bmp (even though that is the directory I was already in!). I will keep exploring to see if I can understand how to fix that. Thanks again.

**Comment by Xalior** [comment]
Looking in a non explicit directory (aka, wherever you happen to be by chance) for an executable is a “*nix-default-no-no” because it’s (thought of as) a horrible security hole - welcome to 1960s computing, and thinking ;-)

-Dx

**Comment by NealeTools** [comment]
Hmmm...I thought that's how I normally did things to be honest...but as I say: I am a *nix novice!

Second issue now, is that I'm not sure what options I need to enable 320.bas code to open/read the -columns output option.
It currently renders scrambled...

**Comment by NealeTools** [comment]
Without the -columns option I get this:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/19664927/123526919-037e8980-d6d3-11eb-9c37-c59fd0947018.png">

**Comment by NealeTools** [comment]
With the -columns option I get this:
<img width="798" alt="image" src="https://user-images.githubusercontent.com/19664927/123526930-21e48500-d6d3-11eb-9363-0c215d11651d.png">

**Comment by NealeTools** [comment]
Whatever option I choose, the output file size is only ~50 kb  = three banks. But, I understand that the 320x256 should be 5 banks (i.e. 80 kb). Any ideas what is going wrong?
<img width="618" alt="image" src="https://user-images.githubusercontent.com/19664927/123527270-f8792880-d6d5-11eb-96f8-7aec289de15a.png">

**Comment by stefanbylund** [comment]
Hi @NealeTools! I'm sorry for replying so late but I had missed to enable e-mail notifications on my GitHub account.

Do you still need help with this?

Regarding your query about the file sizes. A 320x256 BMP file in 8 bits/pixel should, when converted with nextraw, result in an NXI file of size 80.5 KB (82432 bytes).

Which Spectrum Next program (or code snippet) did you use to display the converted 320x256 NXI image?

**Comment by NealeTools** [comment]
Hi Stefan - jsut to say I got this all sorted. My issue back then was assuming that your tools altered the output format to 320x256 = 80K. As expected, if I create a 320x256 8-bit file (80K) .bmp in photoshop and convert that the result is perfect. Thanks so much for this tool!

**Comment by stefanbylund** [comment]
I'm glad you got it sorted. Thanks for your kind words.
