### ISSUE TITLE
Zip file damaged?

### ISSUE THREAD

**Issue by Angar666** [stefanbylund/zxnext_bmp_tools#2]
Hope it's alright reporting here: the ZIP file "ZXNext_BMP_Tools.zip" appears to be corrupted: both 7Zip and WinRAR latest versions flag it as "either unknown format or damaged"...
(Or am I missing something?)

-- Angar

**Comment by Xalior** [comment]
![image](https://user-images.githubusercontent.com/114975/127645697-75df2c91-6b18-42c6-b85d-2ffe58d39e92.png)
It works fine for me...

**Comment by darenm** [comment]
It also works fine for me on WIndows:
![image](https://user-images.githubusercontent.com/1674843/127648976-af66549f-5c1f-47b1-a28c-e9664de6ef99.png)

**Comment by stefanbylund** [comment]
Hi @Angar666! I'm sorry for replying so late but I had missed to enable e-mail notifications on my GitHub account.

I'm closing this issue since the zxnext_bmp_tools.zip ZIP file has been verified as valid ZIP file.
